name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker to GCR
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/flask-service .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/flask-service

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials intelligent-scaler-cluster --zone us-central1-c

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/flask-drl-deployment flask-drl-container=gcr.io/${{ secrets.GCP_PROJECT }}/flask-service
