name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image to Artifact Registry
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/flask-repo/flask-service .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/flask-repo/flask-service

    - name: Install GKE Auth Plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Get GKE Cluster Credentials
      run: |
        gcloud container clusters get-credentials intelligent-scaler-cluster --zone us-central1-c --project ${{ secrets.GCP_PROJECT }}

    - name: Deploy Updated Image to GKE
      run: |
        kubectl set image deployment/flask-drl-deployment flask-drl-container=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/flask-repo/flask-service
